services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "33061:3306"
    networks:
      - flask_app_vpc
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 30s

  flaskapp:
    image: musajoshua/flaskapp:v1.0.5
    restart: always
    container_name: flaskapp
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - flask_app_vpc

networks:
  flask_app_vpc:

volumes:
  mysql_data:

